[env]
# supports arbitrary env vars so mise can be used like direnv/dotenv

[tools]
ruby = "latest"
"ubi:CircleCI-Public/circleci-cli[exe=circleci]" = "latest"
node = "lts"

[tasks.lint]
description = "Lint with Prettier"
run = [
  'npm install prettier',
  'npm exec prettier'
]
hide = true
alias = 'l'

[tasks.bundle]
description = 'Update gem bundle'
run = 'bundle install'
hide = true
alias = 'i'

[tasks.build]
description = 'Build the website'
depends = ['bundle']
run = 'bundle exec jekyll build'
alias = 'b' # `mise run b`

[tasks.server]
description = 'Serve locally the website'
depends = ['bundle']
run = 'bundle exec jekyll server'
alias = 's'
