[lint]
description = "Lint and tidy the code"
run = ['precious lint', 'precious tidy']
hide = true
alias = 'l'

[bundle]
description = 'Bundle'
run = 'bundle'
hide = true

["bundle:install"]
description = 'Install gem dependencies'
run = 'bundle install'
hide = true
alias = 'bi'

["bundle:update"]
description = 'Update gem'
run = 'bundle update'
hide = true
alias = 'bu'

[build]
description = 'Build the website'
depends = 'bundle:install'
run = 'bundle exec jekyll build'
alias = 'b' # `mise run b`

[serve]
description = 'Serve locally the website'
depends = 'bundle:install'
run = 'bundle exec jekyll server'
alias = 's'
